### ISSUE TITLE
GettingStarted: document where to change paths

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#110]
Originally reported by: **routen (Bitbucket: [routen](https://bitbucket.org/routen), GitHub: [routen](https://github.com/routen))**

----------------------------------------

 it needs to be documented where to check/change paths to Polish and WTK

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/34

**Comment by yanokwa** [comment]
No longer relevant.
