### ISSUE TITLE
GettingStarted: ZXlibs assumed, demo project doesn't build

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#111]
Originally reported by: **routen (Bitbucket: [routen](https://bitbucket.org/routen), GitHub: [routen](https://github.com/routen))**

----------------------------------------

ZXing libs is currently assumed by the j2merosa-libraries jar, but needs to be obfuscated out?

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/35

**Comment by yanokwa** [comment]
No longer relevant.
