### ISSUE TITLE
geopoint should support key value pairs

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#113]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

currently, geopoint supports longitude, latitude, altitude and accuracy based on the length of the array. ideally, geo related attributes should be available independent of array length. 

key value pairs seem like the best approach

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/37

**Comment by lognaturel** [comment]
https://forum.opendatakit.org/t/geo-fields-should-be-stored-in-wkt-format-well-known-text/7048 has more discussion about formats for geo data. This would require introducing new types to ensure backwards compatibility.
