### ISSUE TITLE
add line numbers of errors xforms parser

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#114]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

on large forms with errors, it's difficult to track down where the error is without a line number. 

http://groups.google.com/group/open-data-kit/browse_thread/thread/ae482f849b87580d is an example.

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/38

**Comment by lognaturel** [comment]
Almost no user writes forms directly in XML these days so knowing the line number of the failure in the XML source would not be useful. Additionally, by default, pyxform minifies XForms and the line number would always be 1 in that case.

I can't access the original thread so I'm not sure exactly what kind of error this is referring to but I'm guessing it's a runtime error. This still wouldn't be possible to do without major restructuring.
