### ISSUE TITLE
ImageChooserWidget does not activate camera

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#121]
Originally reported by: **Acellam Guy (Bitbucket: [mistaguy](https://bitbucket.org/mistaguy), GitHub: [mistaguy](https://github.com/mistaguy))**

----------------------------------------

The image widget does not activate the camera. am used a couple of Nokia phone of which N95 is among

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/45

**Comment by yanokwa** [comment]
No longer relevant.
