### ISSUE TITLE
need ability to load xforms via usb

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#125]
Originally reported by: **apoku (Bitbucket: [apoku](https://bitbucket.org/apoku), GitHub: [apoku](https://github.com/apoku))**

----------------------------------------

Specifically when dynamically loading any number of forms, it is difficult to have the full JR experience on phones without GPRS service. As of now, once JR has been installed on the phone, the only dynamic option for loading new forms can occur by downloading forms over GPRS.

Proposal is for:
- A way one can load xforms into the application without
pulling them down from a remote server. 
- A way for Xforms to be transferred via USB
- Users should be able to load as many xform(s) as desired after JR has been installed (i.e. Xforms need not be bundled with local build).

See discussion on javaRosa-implementers google group:
http://groups.google.com/group/javarosa-implementers/browse_thread/thread/6d4883d226f645eb

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/49

**Comment by yanokwa** [comment]
No longer relevant.
