### ISSUE TITLE
jr count relevance

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#134]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

https://groups.google.com/forum/?fromgroups#!topic/opendatakit/nHB7K9PIoYs

The second was that the form used "jr:count=" for a repeat and referenced a node that had no answer entered when the user tried to save.  This is actually a bug in javarosa.  The workaround is to make that group relevant only if the node referenced by jr:count is greater than 0.  the relevance check properly handles the empty answer case, jr:count does not.  This bug also causes a crash when trying to use the "jump to" feature, and the workaround also fixes the "jump to" case.

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/58

**Comment by lognaturel** [comment]
This may still be a problem but since it hasn't been reported in many years let's close and reopen if it comes up again.
