### ISSUE TITLE
jr:count in two nested groups

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#135]
Originally reported by: **aurdipas (Bitbucket: [aurdipas](https://bitbucket.org/aurdipas), GitHub: [aurdipas](https://github.com/aurdipas))**

----------------------------------------

What steps will reproduce the problem?
1. create a form with 2 nested group one inside the other.
2. First group is repeated n>1 times where n is a value given to a previous question
3. now group 2 should be repeated p times where p is a value given to a question in group 1.

What is the expected output? What do you see instead?

the group 2 repeated p times. But the application crashes. If as p I assign a value coming from a  question outside group 1 it works

   <input ref="/data/NumberOfHouses">
      <label ref="jr:itext('/data/NumberOfHouses:label')"/>
      <hint ref="jr:itext('/data/NumberOfHouses:hint')"/>
    </input>
  <group>
      <label ref="jr:itext('/data/House:label')"/>
      <repeat nodeset="/data/House" jr:count="/data/NumberOfHouses">
          <input ref="/data/House/numberOfPeopleInHouse">
          <label ref="jr:itext('/data/House/numberOfPeopleInHouse:label')"/>
          <hint ref="jr:itext('/data/House/numberOfPeopleInHouse:hint')"/>
        </input>
        <group>
          <label ref="jr:itext('/data/House/individuals:label')"/>
          <repeat nodeset="/data/House/individuals" jr:count="/data/House/numberOfPeopleInHouse">
            <input ref="/data/House/individuals/permanentId">
              <label ref="jr:itext('/data/House/individuals/permanentId:label')"/>
              <hint ref="jr:itext('/data/House/individuals/permanentId:hint')"/>
            </input>
          </repeat>
        </group>
      </repeat>
    </group>

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/59

**Comment by lognaturel** [comment]
Closed in https://github.com/opendatakit/javarosa/commit/3d28d79d86a4064048af60673e18a306f50a057a and test added in https://github.com/opendatakit/javarosa/commit/b764b92f0df8dea9a209d5d1c324220fa3bd2573.

**Comment by lognaturel** [comment]
> aurdipas created an issue 2012-03-07

@aurdipas, we got you. 😂😂😂😭 (The bug was fixed then, the issue was just never closed for some reason, and no test was added.)
