### ISSUE TITLE
regex failing

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#137]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

Originally filed at http://code.google.com/p/opendatakit/issues/detail?id=546

"I have tried ^[0-9]{10}$ (type is string) to match exactly 10 digits and it works fine except when the first digit is zero. Have tried on version ODK Collect 1.1.7 and 1.2 and same result."

In the test case, I'm using ^[0-9]{5}$, and 012345 passes, but it shouldn't. Interestingly, regex(., '^[0-9]{1}[0-9]{9}$')" works...

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/61

**Comment by alxndrsn** [comment]
@yanokwa is this really a bug?  Running regexes on numbers doesn't sound that useful anyway...

**Comment by yanokwa** [comment]
I think it's a bug because the behavior is unexpected (at least to me) and undocumented. I'm not sure what the best fix is. @lognaturel says we should update the spec to say that regex only works on strings and that folks should cast to string first.

What does Enketo do?

**Comment by alxndrsn** [comment]
Well the spec _does_ say the input's a string - https://opendatakit.github.io/xforms-spec/#fn:regex 😛 

I think if you're collecting 10 digits and expecting to maintain leading zeroes, then it's a string of digits rather than a number anyway.  Can you remember what you were using this for?

**Comment by yanokwa** [comment]
I don't remember what I was using this for, but it was probably a phone number. 

Given what the spec says and the general consensus from @alxndrsn and @lognaturel, I'm closing this issue as not a bug.

**Comment by lognaturel** [comment]
Thanks, @alxndrsn, always nice to see issues closed!! I've replaced this one with a documentation issue -- https://github.com/opendatakit/docs/issues/91
