### ISSUE TITLE
trigger evaluation tree construction leads to unexpected behavior with random()

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#143]
Originally reported by: **Mitch Sundt (Bitbucket: [m.sundt](https://bitbucket.org/m.sundt), GitHub: Unknown)**

----------------------------------------

If you have a simple form with 3 random fields:
<model>
<instance>
  <data id="rtest">
    <r1/>
    <r2/>
    <r3/>
   </data>
  <bind calculate="random()" nodeset="/data/r1" type="decimal" /> 
  <bind calculate="random()" nodeset="/data/r2" type="decimal" /> 
  <bind calculate="random()" nodeset="/data/r3" type="decimal" /> 
</model>

Then the trigger expression construction algorithm incorrectly consolidates the random() calls so that only one call to random() is made, and r1, r2 and r3 are all equal.

The work-around is to add pointless arithmetic to the calculation, which subverts the trigger expression tree algorithm:

  <bind calculate="random() + 0.1 - 0.1" nodeset="/data/r1" type="decimal" /> 
  <bind calculate="random() + 0.2 - 0.2" nodeset="/data/r2" type="decimal" /> 
  <bind calculate="random() + 0.3 - 0.3" nodeset="/data/r3" type="decimal" /> 

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/67

**Comment by lognaturel** [comment]
I had some doubts that this was still an issue and tried to reproduce with 
[multiple-random.xml.txt](https://github.com/opendatakit/javarosa/files/1475626/multiple-random.xml.txt) and 
[multiple-uuid.xml.txt](https://github.com/opendatakit/javarosa/files/1475628/multiple-uuid.xml.txt). Unless I'm misunderstanding the issue, I think this one has been resolved, probably with the alternate DAG implementations that were introduced not that long after.

I thought this might have been related to #199 but with this new information, probably not.
