### ISSUE TITLE
Time component of a dateTime is not accessible in calculates or displays.

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#144]
Originally reported by: **Mitch Sundt (Bitbucket: [m.sundt](https://bitbucket.org/m.sundt), GitHub: Unknown)**

----------------------------------------

1. define a datetime field -- e.g., start preload parameter.
2. attempt to display this.

You should be able to display the time portion of this.  
But only the date portion is accessible.

format-date() also doesn't work -- the time shows as 00:00

Attached is an example form.

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/68

**Comment by lognaturel** [comment]
Closed in favor of #226.
