### ISSUE TITLE
count-selected(...) not equal to zero when no items are selected

### ISSUE THREAD

**Issue by batkinson** [opendatakit/javarosa#158]
#### Software versions 
Tested on versions of javarosa used in collect 1.4.16 and 1.8.1

#### Problem description
It appears that the count-selected(...) function doesn't return the value zero when there are no items selected. This makes constraining selections to zero-or-more items impossible (or at least more complicated than you would expect, if possible).

#### Steps to reproduce the problem

Use the attached [test form](https://github.com/opendatakit/javarosa/files/1186858/repeat-zero-defect.zip) and enter the following values when prompted:

1. Number of individuals: 2
2. Individual(1) Name: Sally
3. Individual(2) Name: Bob
4. Number of groups: 2
5. Group(1) Number of individuals in this group: 1
6. Group(1) Which individuals are in this group: (select a single person, you can see more or less than one works as expected)
7. Group(2) Number of individuals in this group: 0
8. Group(2) Which individuals are in this group: (attempt swiping and you see you can't regardless of the items selected)

#### Expected behavior
You should be able to swipe past the question since the selected count matches zero.

While the semantics seem contrived for the test form (since you can use a relevance to hide the multi-select in the zero case), it appears to demonstrate that count-selected never equals zero. This seems to suggest that you can't define a rule using where zero is also acceptable without doing something more complicated. It seems zero should be a valid result of count-selected(...).

**Comment by lognaturel** [comment]
Peculiar. I took a quick look through and am not seeing any reason it wouldn't be 0. I didn't think through the `DateUtils.split` method in detail, though. @dcbriccetti how about looking at this one after #51 and #157?

**Comment by dcbriccetti** [comment]
OK. Have you thought any more about using “assign to”? It makes it easier for me to track what I’m working on.

**Comment by dcbriccetti** [comment]
JavaRosa’s ```FormEntryController.answerQuestion``` doesn’t get as far as evaluating the constraint because ```data``` is null and the element is required. (```data``` is null because no checkboxes were checked.)

![screen shot 2017-08-05 at 11 13 34 am](https://user-images.githubusercontent.com/55099/28997698-acf7ed54-79cf-11e7-9185-45459b9cc42f.png)

When I removed `required="true()"` from this line, Collect allowed me to swipe past the question.

```<bind nodeset="/data/group/members" constraint="count-selected(.) = ../num_members" required="true()" type="select"/>```

**Comment by dcbriccetti** [comment]
A better title might be “Can’t swipe past empty itemset if required="true"”

**Comment by batkinson** [comment]
You are right @dcbriccetti and that makes perfect sense. I had a bit of tunnel-vision after looking at a much larger form design for too long. The test form was a reduction of a much longer form and that detail was lost in the noise.  

The intended design just needs to use a calculation for the required attribute, like the following:

```
<bind nodeset="/data/group/members" constraint="count-selected(.) = ../num_members" required="../num_members > 0" type="select"/>
```

I tested this alternative, and it is working as I believe the original design intended. Sorry for the premature report. I will look a little more closely next time. Thank you both @lognaturel and @dcbriccetti.

**Comment by dcbriccetti** [comment]
@batkinson, it was a learning exercise for me, and didn’t take long. Glad we could help.

**Comment by lognaturel** [comment]
Ahh, interesting! No worries @batkinson and thanks for that explanation @dcbriccetti. 🙏

**Comment by lognaturel** [comment]
I'll add -- better to report something that turns out not to be a bug than to risk living with something that is!!
