### ISSUE TITLE
Add support for external secondary instances

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#16]
#### Software versions 
JavaRosa v2016-04-21

#### Problem description
The status of external secondary instance support is unknown.

[External secondary instances](https://opendatakit.github.io/xforms-spec/#secondary-instances---external) are now part of the ODK XForms spec. As discussed in opendatakit/xforms-spec#50, there is at least partial support for the concept in JavaRosa currently.

I think the first step to addressing this should be to figure out what the state of the current implementation is and if/how it is usable. Then I believe there will need to be some design work done to make sure that the implementation is practical for large external secondary instances.

**Comment by dcbriccetti** [comment]
I don’t see any evidence of support for external secondary instances in ODK’s JavaRosa. I looked at CommCare’s JavaRosa code and added just a bit of code to ODK’s to recognize the src attribute of the instance element. https://github.com/opendatakit/javarosa/pull/34 .

A next step might be to design a form and some tests, to define what we want to implement.

**Comment by dcbriccetti** [comment]
Oh boy, it looks like Dimagi had to modify even the XPath code when generalizing FormInstance references to DataInstance (abstract parent of FormInstance and ExternalDataInstance). The concrete FormInstance occurs in more than 26 files in the xpath packgae, according to IDEA. I didn’t get a sense of this magnitude from Clayton Sims when we spoke with him on April 7. My notes from that call include the now-impenetrable “in code, ignore external data model, look for instance into actual dom”, which makes me want to have Clayton confirm that these extensive changes to the xpath package are required.

**Comment by lognaturel** [comment]
Did you follow the links [here](https://github.com/opendatakit/xforms-spec/issues/50#issuecomment-277174668)? In particular, [the loading of secondary instances](https://github.com/opendatakit/javarosa/blob/3eb73b5c8c1d56b9bd635b1aca6a8e9ab1051fa9/core/src/org/javarosa/xform/parse/XFormParser.java#L439) and [the map they are stored in](https://github.com/opendatakit/javarosa/blob/3eb73b5c8c1d56b9bd635b1aca6a8e9ab1051fa9/core/src/org/javarosa/core/model/FormDef.java#L206). I believe `DataInstance` is for convenience/speed.

I agree that some sample forms and tests around them would be helpful.

**Comment by dcbriccetti** [comment]
There is support for secondary instances on ODK JavaRosa, but not _external_ ones. Or are you talking about something else?

**Comment by lognaturel** [comment]
Ah, I see. Ok, so I guess the next question is what is the minimal change needed to handle external ones.

**Comment by lognaturel** [comment]
To be more specific, CommCare has much stricter performance requirements since case management depends heavily on reading past data and making complex queries over it. I think we could set more modest performance targets if that could allow for a simpler implementation. 

From an external functionality standpoint, [this](https://bitbucket.org/javarosa/javarosa/wiki/externalinstances) is what needs to be supported.

[This](https://github.com/dimagi/commcare-core/wiki/Technical-Details-on-Performance) describes  how Dimagi's JavaRosa approaches performance.

**Comment by dcbriccetti** [comment]
In 2011, Clayton made this large change, including generalizing FormInstance to DataInstance. Can we ask him if we are looking at a similar change?
https://github.com/dimagi/commcare-core/commit/3bc5c1abe7bec87639baf831637ded6f48ac5839

**Comment by lognaturel** [comment]
Cool, that looks like where external secondary instances start being supported? With the loading [here](https://github.com/dimagi/commcare-core/blob/3bc5c1abe7bec87639baf831637ded6f48ac5839/core/src/org/javarosa/xform/parse/XFormParser.java#L335)? If you have some specific questions, you can always tag @ ctsims!

**Comment by dcbriccetti** [comment]
Yes, that’s the place. I tagged @ctsims above. Thanks.

**Comment by dcbriccetti** [comment]
I’ve managed to change just 28 files, and make the FormInstance to DataInstance change. I’ll commit that in the branch later.

**Comment by dcbriccetti** [comment]
@ctsims Hi. I wonder if we could meet again, even briefly.

**Comment by ctsims** [comment]
Hi Dave,

Definitely!

Can we chat again this Friday?

-Clayton

**Comment by dcbriccetti** [comment]
Can I reach you by email or Skype? Mine are daveb@davebsoft.com and “Dave Briccetti”.

**Comment by dcbriccetti** [comment]
Very brief notes on this topic from my short conversation with @ctsims on 4/27:

- Get next step for bringing in an external secondary instance.
	- Is creating an ExternalDataInstance (as Dimagi did) the right approach for ODK?
		- Yes
	- How to read the file and load into the DOM?
		- Look at their InstanceInitializationFactory
		- In FormDef.initialize pass in something that tells how to turn into tree element
		- match jr:// .. xml
		- insert at TreeElement
		- cache these files
