### ISSUE TITLE
Add count-non-empty XForms 1.0 function 

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#163]
As described in opendatakit/xforms-spec#127 along with some tests.

This one should be approachable for a new contributor. The place to start looking is in [XPathFuncExpr](https://github.com/opendatakit/javarosa/blob/37effe59710b272c1d57f775eba422ff8474bed6/src/org/javarosa/xpath/expr/XPathFuncExpr.java). In particular, there are other examples that take nodesets as parameters. Join us in the #javarosa-code channel of [the Slack](slack.opendatakit.org) with any questions! 

Let's get this in the August release so pyxform can get the update. If no one picks it up in the next couple of weeks, @dcbriccetti it might be a nice palate cleanser between some of the more open-ended, tricky things you're looking at.

**Comment by danielrees18** [comment]
@opendatakit-bot claim
