### ISSUE TITLE
Add digest function

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#164]
opendatakit/xforms-spec#103 (use [this spec](https://www.w3.org/TR/xforms/#fn-digest))

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
@hooverlunch I know this is something you wanted. It's now in the latest Collect beta -- https://forum.opendatakit.org/t/odk-collect-v1-13-beta/11902! Please check it out and make sure it works for your needs.

If you use XLSForm, pyxform will need to be run with Validate disabled until the next Validate release.

**Comment by hooverlunch** [comment]
Cool! Thanks! Looks good to me...
