### ISSUE TITLE
DataInstance not instantiable exception

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#180]
There's a new stack trace showing up frequently in Firebase Crash since the 1.10.0 Collect release that has support for external secondary instances. It presumably has to do with blank forms being serialized for use on first open but I can't reproduce it.

Firebase reports this as non-fatal but it's not always accurate. 

@grzesiek2010 is also looking for a way to repro. @dcbriccetti perhaps you have some ideas from looking at the trace?

```
Exception org.javarosa.core.util.externalizable.CannotCreateObjectException: org.javarosa.core.model.instance.DataInstance: not instantiable
org.javarosa.core.util.externalizable.PrototypeFactory.getInstance (PrototypeFactory.java:133)
org.javarosa.core.util.externalizable.ExtUtil.read (ExtUtil.java:185)
org.javarosa.core.util.externalizable.ExtWrapBase.readExternal (ExtWrapBase.java:56)
org.javarosa.core.util.externalizable.ExtUtil.read (ExtUtil.java:220)
org.javarosa.core.util.externalizable.ExtWrapMap.readExternal (ExtWrapMap.java:127)
org.javarosa.core.util.externalizable.ExtUtil.read (ExtUtil.java:220)
org.javarosa.core.util.externalizable.ExtUtil.read (ExtUtil.java:216)
org.javarosa.core.model.FormDef.readExternal (FormDef.java:1215)
org.odk.collect.android.tasks.FormLoaderTask.deserializeFormDef (FormLoaderTask.java:476)
org.odk.collect.android.tasks.FormLoaderTask.doInBackground (FormLoaderTask.java:150)
org.odk.collect.android.tasks.FormLoaderTask.doInBackground (FormLoaderTask.java:73)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)
```

**Comment by dcbriccetti** [comment]
Yikes. I’ll take a look.

**Comment by grzesiek2010** [comment]
I can see the same logs but everything works well so it's not a blocker for us.

**Comment by dcbriccetti** [comment]
Thanks, @grzesiek2010. If you find a way to reproduce, I’d like to understand and fix it.

**Comment by grzesiek2010** [comment]
1. Uninstall your current ODK Collect app and remove the odk folder from your device (not sure if it's necessary to reproduce but just in case. Just install fresh app)
2. Download one of available form (in my case it was cascading select form but I'm sure it's not important).
3. Open this form and save.
4. Try to open saved instance (Edit form) and you should be able to see the same logs.

**Comment by lognaturel** [comment]
👏 Thanks, @grzesiek2010! Great to know it's not a show-stopper. The repro steps make sense -- I was only thinking about the blank forms but of course it's instance related. I believe the implication is that it is now slower to load forms for editing because the cached version isn't available. Great that Collect handles that gracefully. @dcbriccetti it would be great to have a fix soon-ish but it's not a 🔥🔥🔥🚒👨‍🚒👩‍🚒

**Comment by dcbriccetti** [comment]
I can reproduce, and I see the cause (trying to create a DataInstance, where DataInstance is abstract).

**Comment by dcbriccetti** [comment]
I think I found the problem, and if so it’s a very simple change to one line of code in `FormDef.readExternal`. I’ll do more testing tomorrow.

**Comment by dcbriccetti** [comment]
@grzesiek2010 (or anyone), feel free to test the change above, if you’re so inclined, and equipped to do so. I probably won’t return to the problem until about 11:30 AM PDT.

**Comment by lognaturel** [comment]
Great, thanks @dcbriccetti! Isn't it fun working with people around the world so there's progress around the clock??

**Comment by grzesiek2010** [comment]
I can confirm it works.

**Comment by dcbriccetti** [comment]
>I can confirm it works.

Thanks!
