### ISSUE TITLE
Cannot parse 'eIMCI by D-Tree' form and a form with template repeat

### ISSUE THREAD

**Issue by mdudzinski** [opendatakit/javarosa#202]
#### Software versions 
JavaRosa v2.6.0-SNAPSHOT, Mac OS 10.12.6

#### Problem description
It is no longer possible to parse some of the forms after performance improvements (#192). Example of forms long with unit tests are available [here]
(https://github.com/mdudzinski/javarosa/commits/form-parsing-code-coverage) (the latest 2 commits)

* eIMCI by D-Tree

> java.lang.NullPointerException
> 	at org.javarosa.xform.parse.XFormParser.allChildrenHaveTheSameName(XFormParser.java:1869)
> 	at org.javarosa.xform.parse.XFormParser.buildInstanceStructure(XFormParser.java:1836)
> 	at org.javarosa.xform.parse.XFormParser.buildInstanceStructure(XFormParser.java:1839)
> 	at org.javarosa.xform.parse.FormInstanceParser.parseInstance(FormInstanceParser.java:60)
> 	at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:445)
> 	at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:326)
> 	at org.javarosa.xform.parse.XFormParserTest.parse(XFormParserTest.java:302)
> 	at org.javarosa.xform.parse.XFormParserTest.parseIMCIbyDTreeForm(XFormParserTest.java:279)

* simple form with template repeat

> java.lang.IllegalStateException: Unexpected multiplicity mismatch
> 
> 	at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:266)
> 	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:217)
> 	at org.javarosa.xform.parse.FormInstanceParser.flagRepeatables(FormInstanceParser.java:114)
> 	at org.javarosa.xform.parse.FormInstanceParser.processRepeats(FormInstanceParser.java:105)
> 	at org.javarosa.xform.parse.FormInstanceParser.parseInstance(FormInstanceParser.java:81)
> 	at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:445)
> 	at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:326)
> 	at org.javarosa.xform.parse.XFormParserTest.parse(XFormParserTest.java:302)
> 	at org.javarosa.xform.parse.XFormParserTest.parseFormWithTemplateRepeat(XFormParserTest.java:270)

#### Steps to reproduce the problem

Two ways:
* Run the recently added tests from [the branch in my fork of JavaRosa](https://github.com/mdudzinski/javarosa/commits/form-parsing-code-coverage)
* Try to load those forms using ODK Collect. Some more details can be found [here](https://github.com/opendatakit/collect/pull/1527).

#### Expected behavior

Forms can be parsed and loaded.

#### Other information 
Both are caused by 8a71020012dc15a8c28d644eddbccc7e8a777bd2

**Comment by mdudzinski** [comment]
The cause of the NPE:
![npe-cause](https://user-images.githubusercontent.com/1262799/31771839-d413f8ee-b4dd-11e7-9337-f56002ef08dc.png)
`Element#getElement(int index)` returns null if an element at the index position is not an instance of `Element`

**Comment by mdudzinski** [comment]
@dcbriccetti
For 'eIMCI by D-Tree' problem I see two options:
* Fix `XFormParser#allChildrenHaveTheSameName(Element node)` so it's aware that the first child may not be an element
* Get rid of text children before accessing this method

First option should be easy but I've got strong feeling that this kind of problem may come back in the future so I'm thinking about option two. 
`XmlTextConsolidato` takes care of text children that contain only whitespaces . Are non-empty text children actually needed?

**Comment by lognaturel** [comment]
I think stripping comments from the model the same way empty whitespace lines are stripped is the way to go since comments are only human-facing. The eIMCI form was a good one to verify because it's a rare one that's still around that was built in raw XML (hence the comments).

**Comment by dcbriccetti** [comment]
Nice work, @mdudzinski!
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
I think I have a simpler, safer solution to the first problem.
![screen shot 2017-10-19 at 12 05 47 pm](https://user-images.githubusercontent.com/55099/31789191-2bea2eca-b4c6-11e7-9643-3e59cab59851.png)

**Comment by lognaturel** [comment]
I believe that was @mdudzinski's first option if I'm understanding correctly. His point is that having non-Elements as children of elements is likely to cause problems elsewhere.

That said, it's been that way for a long time...

**Comment by dcbriccetti** [comment]
Oh, you’re right. And not just the first child. 

I’m inclined to wait until we can identify other such problems (existing before this optimization) before we attempt to fix them.

**Comment by lognaturel** [comment]
That sounds like a good plan.

It would be really nice to document these kinds of gotchas somewhere so they're not just living in our heads. Maybe above the `null` check you could say something like "Comments in the XML are represented as Strings, not Elements" or something of that nature.

I think you've also been keeping some notes for eventual dev docs and the fact that `Element`s can have non-`Element` children would be a good small thing to keep track of.

**Comment by dcbriccetti** [comment]
I think you’ll like the new tests that are coming, such as 
```
    @Test public void discoversNonElementChild() {
        Element el = new Element();
        el.addChild(COMMENT, "A string");
        assertFalse(XFormParser.allChildrenAreElementsAndHaveTheSameName(el));
    }
```

**Comment by lognaturel** [comment]
💜

**Comment by dcbriccetti** [comment]
I think I’ll test this NPE fix against the form in collect, then make a PR for this single fix. Then work on the other.

**Comment by mdudzinski** [comment]
@dcbriccetti  @lognaturel 
I'm a little bit sad that we didn't decide to get rid of those non-`Element` children but I get the reason :)

**Comment by lognaturel** [comment]
@mdudzinski The door is still open for that change later on! 😊

**Comment by dcbriccetti** [comment]
I’ve found the problem causing the frightening `IllegalStateException("Unexpected multiplicity mismatch")`. The code that checks to see if optimizations can be performed on the TreeElement children, `allChildrenAreElementsAndHaveTheSameName`, doesn’t notice when a child has a `template` attribute. Should be a quick fix.
