### ISSUE TITLE
Exception java.lang.ClassCastException: org.javarosa.core.model.data.UncastData cannot be cast to org.javarosa.core.model.data.StringData

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#210]
#### Software versions 
JavaRosa v2.6.0

#### Problem description

We can use other types than string for `instanceName`.

> Exception java.lang.ClassCastException: org.javarosa.core.model.data.UncastData cannot be cast to org.javarosa.core.model.data.StringData
org.odk.collect.android.logic.FormController.getSubmissionMetadata (FormController.java:1183)
org.odk.collect.android.utilities.TimerLogger.<init> (TimerLogger.java:171)
org.odk.collect.android.logic.FormController.getTimerLogger (FormController.java:200)
org.odk.collect.android.activities.FormEntryActivity.showNextView (FormEntryActivity.java:1475)
org.odk.collect.android.activities.FormEntryActivity.onFling (FormEntryActivity.java:2899)

#### Steps to reproduce the problem
Use one of the attached forms:
[1560_DateData.xml.txt](https://github.com/opendatakit/javarosa/files/1426494/1560_DateData.xml.txt)
[1560_IntegerData.xml.txt](https://github.com/opendatakit/javarosa/files/1426495/1560_IntegerData.xml.txt)

Open the form and try to swipe.

#### Other information 
The problem is not related only to `instanceName`. I can do the same with `instanceID` for example using this form: 
[1560_IntegerData_instanceID.xml.txt](https://github.com/opendatakit/javarosa/files/1426500/1560_IntegerData_instanceID.xml.txt)

I think it's a bug and it should be always StringData. Am I right or we should support other types too?
@lognaturel @dcbriccetti

**Comment by lognaturel** [comment]
Now that I've reflected more deeply on this, I think we can probably handle it all on the Collect side. It shouldn't be a problem to have instance names or IDs of types other than strings. We should just be using their string representations. Here's a possible approach to verify: https://github.com/opendatakit/collect/issues/1560#issuecomment-340564402
