### ISSUE TITLE
Only a value in one group is recalculated after removing group.

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#213]
#### Software versions 
JavaRosa v2.6.0

#### Problem description
I have a form with repeat group. The value of the first question is calculated `calculate="position(..)"`
If I remove one group, only the value in the next one is recalculated.

#### Steps to reproduce the problem
1. Open the attached form.
2. Add three groups
3. Go back to the first group and delete it.

#### Expected behavior
All values should be recalculated I think. But if I go to the second question it's still 3 like before.

#### Other information 
[RepeatGroupWithPosition.xml.txt](https://github.com/opendatakit/javarosa/files/1430192/RepeatGroupWithPosition.xml.txt)

**Comment by lognaturel** [comment]
This is a really interesting case, @grzesiek2010!

Certainly the behavior should be consistent across groups. As you say, the question is whether everything should be reevaluated on deletion of one repeat or not. I think the answer is yes. @mdudzinski you've already looked deeply into repeat and group deletion, could you please take a look at this?

**Comment by mdudzinski** [comment]
@lognaturel Sure, I'll!

@opendatakit-bot claim

**Comment by mdudzinski** [comment]
@lognaturel I'm still investigating this. This is related to `IDag` implementations. There is a code that is responsible for triggering calculations upon a repeat group deletion but it never gets to the "position" condition in `XPathFuncExpr` class. Not sure why but anyway this code doesn't seem to be going over all repeats and recalculating values for each repeat group instance. This seems to be - relatively - easy to implement but may have an impact on the performance of the delete operation. If there are a lot of repeat groups with a lot of nodes with a lot of calculations. I think only a small subset - if not only the "position" function, I haven't gone over all of them - of xpath functions depend on the parent repeat group position. So the ideal implementation would trigger recalculation only if there are such functions. And this might much more complex to implement. 
Just want to confirm if we first should fix this in the easiest way possible and test the performance (there is a chance it won't be noticeable) or we want to go with the ideal implementation right away.

**Comment by lognaturel** [comment]
This is maybe a naive or irrelevant question but why can't they recalculate on swipe? Isn't that the behavior for other fields or am I mistaken?

**Comment by mdudzinski** [comment]
@lognaturel Calculations are fired when:
* An answer is committed
* A new repeat is added
* A repeat is deleted

We could implement recalculations on a swipe but it wouldn't be consistent with the current flow.

There is an interesting code that holds a map of `TreeReference` => `ArrayList<QuickTriggerable>`. Whenever a value of value a node at certain tree reference changes, all related calculations are fired. We could fix the behavior of the repeat group deletion in a similar way.

**Comment by lognaturel** [comment]
Yes, I suppose I was thinking of the answer committed case. The position change feels like an answer being committed but I suppose it's not.

So it sounds like there are three options?
- When one repeat is deleted, iterate over all repeats and recompute
- When one repeat is deleted, see if any fields contain XPath functions that depend on the parent position and if so recompute
- Keep track of all related repeats and recompute when one is deleted

I'm not totally sure I framed the last one correctly and whether it's actually different from the first.

I think trying the simplest approach first is the way to go.

**Comment by mdudzinski** [comment]
@lognaturel Well, deleting a repeat actually triggers recalculation but only for the next repeat after the deleted one. So you're right that the position change feels like an answer being committed :)

Actually I was thinking about two options. The last one seems to be the same as the first. 
But now I think there may be a third, completely different option. Calculations are triggered when an answer is committed. ODK Collect validates answers (by committing them again) on:
* swipe (`saveAllScreenAnswers` method)
* form save (`formController.validateAnswers(markCompleted)` in `SaveToDiskTask`)

I think both should update calculated answers based on the parent position. Somehow, such calculations are not triggered. 

I'll compare effort for this approach and iterate over all repeats and recompute.
