### ISSUE TITLE
Indexed-repeat error when index is blank

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#214]
#### Software versions 
JavaRosa v2.6.0

#### Problem description
Form and error posted at https://forum.opendatakit.org/t/indexed-repeat-error-for-previously-defined-integer-as-the-third-argument/10442

#### Steps to reproduce the problem
Read the form above in Collect. The error shows up when the second household member is added.

#### Expected behavior
No error, this should be a valid form.

#### Other information 
The problem seems to be that `index1` initially has no value. I was able to get this to work by defining a default of `1`.

**Comment by mdudzinski** [comment]
@opendatakit-bot claim
