### ISSUE TITLE
Warning displayed when rows attribute is used on an input node.

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#236]
#### Problem description
Warning displayed when `rows` attribute is used on an `input` node.

#### Steps to reproduce the problem
Add the `rows` attribute to a text field:
```
        <input ref="/data/comments" rows="2">
          <label>Comments</label>
        </input>
```
This is recognized and used by Collect and perhaps other clients but the following warning is shown using Validate:
```
Problem found at nodeset: 
    With element <input ref="/data/comments" rows="2"><label>
```

#### Expected behavior
No warning.

#### Other information 
I guess we should specifically allow `rows`. Another option would be to allow any attribute but that might be less helpful.

**Comment by lognaturel** [comment]
Similarly `requiredMsg` is not recognized. I think the right thing to do is to add these to `usedAtts` [here](https://github.com/opendatakit/javarosa/blob/2e2030906e96f14a04629a2e0961d3d6408932df/src/org/javarosa/xform/parse/XFormParser.java#L1701). @dcbriccetti @yanokwa? Any reason not to?

**Comment by yanokwa** [comment]
I think maintaining a whitelist of attributes is the right thing to do. 

The current list is at https://opendatakit.github.io/xforms-spec/#bind-attributes and we are missing the following:

* requiredMsg
* saveIncomplete

**Comment by daveycrockett** [comment]
@opendatakit-bot claim

**Comment by daveycrockett** [comment]
@opendatakit-bot claim

**Comment by daveycrockett** [comment]
See my current [PR](https://github.com/opendatakit/javarosa/pull/237). It looks like (to this beginner) that the fix may be more involved, any feedback welcome! Otherwise I'll keep poking at it.

**Comment by dcbriccetti** [comment]
There are two places where
```
protected QuestionDef parseControl(IFormElement parent, Element e, int controlType, List<String> additionalUsedAtts) {
```
is called with additionalUsedAtts. One is for range (which I added last May):

```
put("range", new IElementHandler() {
    @Override public void handle(XFormParser p, Element e, Object parent) {
        p.parseControl((IFormElement) parent, e, Constants.CONTROL_RANGE,
                Arrays.asList("start", "end", "step") // Prevent warning about unexpected attributes
        );
    }
});
```
The code for input looks like this now:
```
put("input", new IElementHandler() {
    @Override public void handle(XFormParser p, Element e, Object parent) {
        p.parseControl((IFormElement) parent, e, Constants.CONTROL_INPUT);
    }
});
```
Perhaps we want to add additional attributes for input.

**Comment by lognaturel** [comment]
I'm sorry, I think what I linked to is just the whitelist for `bind`. Different element types build their own lists when being parsed. But I would think that would be the right place for `requiredMsg` and and `saveIncomplete`? Looks like @dcbriccetti has identified where `rows` needs to be added.

**Comment by daveycrockett** [comment]
Thank you for the clarification, this makes sense! I've created a new PR that incorporates these changes into a single clean commit.
