### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/javarosa#243]
Add a CODE_OF_CONDUCT.md file just like Collect. https://github.com/opendatakit/collect/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by AkshitOstwal** [comment]
you mean add this 
Please refer to the project-wide [ODK Code of Conduct](https://github.com/opendatakit/governance/blob/master/CODE-OF-CONDUCT.md).
?? 
or something similar to this in

**Comment by yanokwa** [comment]
@AkshitOstwal Yup!

**Comment by neal0892** [comment]
@yanokwa  Please review.

**Comment by lognaturel** [comment]
Thank you, @neal0892!
