### ISSUE TITLE
DeserializationException with All_widgets.xml form

### ISSUE THREAD

**Issue by dcbriccetti** [opendatakit/javarosa#245]
#### Software versions 
JavaRosa v2.7.0

#### Problem description
org.javarosa.core.util.externalizable.DeserializationException: No datatype registered to serialization code [d8 60 b9 d1]

#### Steps to reproduce the problem
Add a test to XFormParserTest:
```
@Test public void allWidgetsFormSavesAndRestores() throws IOException, DeserializationException {
    serAndDeserializeForm(r("All_widgets.xml"));
}
```
#### Expected behavior
Not the exception.
#### Other information 
I’m guessing there’s a class being serialized that isn’t registered with JavaRosa, and that it needs to be added here: https://github.com/opendatakit/javarosa/blob/15a825805a3f5976a908d0e8a1b65c7f8642cf96/src/org/javarosa/core/model/CoreModelModule.java#L26

[All_widgets.xml.txt](https://github.com/opendatakit/javarosa/files/1717676/All_widgets.xml.txt)

**Comment by mdmahendri** [comment]
you are right, `range` element is not registered in `CoreModelModule`
@opendatakit-bot claim
