### ISSUE TITLE
Doubled tree element that represents a repeat group 

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#248]
Working on https://github.com/opendatakit/collect/pull/1851 I have noticed an issue on the Javarosa's side which I started describing [here](https://opendatakit.slack.com/messages/C389J6X0W/) two days ago. 

The problem is sometimes when I use repeat groups a TreeElement that represents such a group is doubled, please look here:
![formdef](https://user-images.githubusercontent.com/3276264/36317037-429256e6-133c-11e8-9526-f9cf612056dc.png)

I decided to investigate the code and fix the issue and here are my thoughts:
It's doubled because it's added here as a missing https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/xform/parse/FormInstanceParser.java#L446
why?
because `template` one line above is null.
why?
because [resolveReference](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/DataInstance.java#L74) returns null.
why?
because [result](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/DataInstance.java#L107) is null.
why?
because when we try to read this value here https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/DataInstance.java#L101 we use `name="Tree"` and `mult=0`
hmmm name is ok but `mult = 0` as I noticed when an element is repeatable it should be `-2` it's even written here https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/TreeReference.java#L57
debugging other forms with repeat groups I noticed it's always `-2` but here I have `0`.
why?
because [isTemplate(node)](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/xform/parse/XFormParser.java#L1809) returns false form that node which represents repeatable group. I tested again other forms with repeat groups and I noticed it returns true in such cases. Ok so I analyzed my form and I noticed that there is lack of  `jr:template=""` in group start-tag.
```
      <instance>
        <data id="build_FormWIthRepeatGroup_1518798393">
          <meta>
            <instanceID/>
          </meta>
          <Text/>
          <G1>
            <Text2/>
          </G1>
        </data>
      </instance>
```
here is how it looks in other forms I tested which work well:
```
      <instance>
        <data id="build_FormWIthRepeatGroup_1518798392">
          <meta>
            <instanceID/>
          </meta>
          <Text/>
          <G1 jr:template="">
            <Text2/>
          </G1>
        </data>
      </instance>
```

Both forms for testing:
[FormWIthRepeatGroupBad.xml.txt](https://github.com/opendatakit/javarosa/files/1732007/FormWIthRepeatGroupBad.xml.txt)
[FormWIthRepeatGroup.xml.txt](https://github.com/opendatakit/javarosa/files/1732008/FormWIthRepeatGroup.xml.txt)

It's not only my form because the problem has been found using the `Forest Plot Surver` available on our demo server.

About `jr:template=""` I know only one thing: if we remove that the first group is added without asking us.
So if we can remove  `jr:template=""` we probably shouldn't relay only on it?

@dcbriccetti @yanokwa @lognaturel what do you think?

**Comment by dcbriccetti** [comment]
I don’t know enough about this. I’ll pause to see if someone jumps in with answers.

**Comment by grzesiek2010** [comment]
@mdudzinski I don't know (not in the code I discovered as I remember) but I'm sure it's not related to serialization. The problem is that we use `jr:template=""` for repeat groups but sometimes it doesn't exist it's not necessary.

**Comment by lognaturel** [comment]
See my comment at https://github.com/opendatakit/javarosa/issues/266#issuecomment-369724087 for more about what `jr:template` is for. If `jr:template=""` is not included on a `repeat` then that repeat group is part of the record.

> So if we can remove jr:template="" we probably shouldn't relay only on it?

Can you say more about what you mean by this? Forms with and without `jr:template` are supposed to have different behavior. It sounds like maybe that wasn't clear to you and you expected the two to behave the same?

I'm hoping that the extra information on what `jr:template` means will help! If you still think there's a bug here we can dig deeper.

**Comment by grzesiek2010** [comment]
> Can you say more about what you mean by this? Forms with and without jr:template are supposed to have different behavior.

I thought we always set multiplicity for `-2` (for repeats) even if it doesn't have `jr:template` but looking at the code it's `-2` if `jr:template` exists and 0 otherwise what cause the problem with a doubled element.

**Comment by grzesiek2010** [comment]
> Can you say more about what you mean by this? Forms with and without jr:template are supposed to have different behavior. It sounds like maybe that wasn't clear to you and you expected the two to behave the same?

I thought we use multiplicity `-2` for all repeats but it's for templates only my bad. But I'm still not sure why we need to double that element...

**Comment by grzesiek2010** [comment]
After working on repeat sections in Collect I understand it better. I think it works as expected similar to #266 so I'll close this issue.
