### ISSUE TITLE
DigestAlgorithmTest fails with mvn but not gradle

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/javarosa#251]
#### Software versions 
JavaRosa master

#### Problem description
We use gradle to build the jar for development, but mvn is what we use to package the jar for release. On master, `./gradlew test` works great, but `mvn test` fails with 

```
Tests in error:
  doTests(org.javarosa.xpath.test.XPathEvalTest): javax/xml/bind/DatatypeConverter
  doTestsInPolishLocale(org.javarosa.xpath.test.XPathEvalTest): javax/xml/bind/DatatypeConverter
  encodes_byte_arrays[Hexadecimal](org.javarosa.xpath.expr.EncodingTest): javax/xml/bind/DatatypeConverter
  encodes_byte_arrays[Base64](org.javarosa.xpath.expr.EncodingTest): javax/xml/bind/DatatypeConverter
  generates_a_digest[MD5](org.javarosa.xpath.expr.DigestAlgorithmTest): javax/xml/bind/DatatypeConverter
  generates_a_digest[SHA-1](org.javarosa.xpath.expr.DigestAlgorithmTest): javax/xml/bind/DatatypeConverter
  generates_a_digest[SHA-256](org.javarosa.xpath.expr.DigestAlgorithmTest): javax/xml/bind/DatatypeConverter
  generates_a_digest[SHA-384](org.javarosa.xpath.expr.DigestAlgorithmTest): javax/xml/bind/DatatypeConverter
  generates_a_digest[SHA-512](org.javarosa.xpath.expr.DigestAlgorithmTest): javax/xml/bind/DatatypeConverter
```

#### Other information 

I have not looked deeply, but my guess is that there test classes are not in the place mvn expects.

[org.javarosa.xpath.expr.DigestAlgorithmTest.txt](https://github.com/opendatakit/javarosa/files/1737854/org.javarosa.xpath.expr.DigestAlgorithmTest.txt)
[org.javarosa.xpath.expr.EncodingTest.txt](https://github.com/opendatakit/javarosa/files/1737855/org.javarosa.xpath.expr.EncodingTest.txt)
[org.javarosa.xpath.test.XPathEvalTest.txt](https://github.com/opendatakit/javarosa/files/1737856/org.javarosa.xpath.test.XPathEvalTest.txt)

**Comment by ggalmazor** [comment]
Is it possible that maven and gradle use different jdks?

**Comment by ggalmazor** [comment]
Also, can't reproduce the error with `mvn test`. 

`mvn -version` tells 3.5.2
`java -version` tells 1.8.0_161

**Comment by yanokwa** [comment]
I can't reproduce this on CircleCI, so I'm guessing that you are correct and that it's because of my multiple MVN setup.

**Comment by ggalmazor** [comment]
I totally recommend [SDKMan](http://sdkman.io)!

**Comment by lognaturel** [comment]
`mvn test` succeeds on mvn 3.5.0, java 1.8.0_112. (maybe I'm due for some updates)

**Comment by yanokwa** [comment]
I'm using jenv.be instead of SDKMan and it's been working great until now. I can confirm that my mvn is using Java 9.

```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T00:58:13-07:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 9.0.4, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
```

To fix, I added created a `~/.mavenrc` file with `JAVA_HOME=$(echo /Library/Java/JavaVirtualMachines/jdk$(jenv local)*/Contents/Home)`
