### ISSUE TITLE
Remove use of javax api not included in Android

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#256]
#### Software versions 
JavaRosa v1.8.0

#### Problem description
#247 uses some classes from `javax` that are not included in Android. Unfortunately that makes JR unusable so an alternative will need to be considered.

CC @ggalmazor @dcbriccetti

**Comment by dcbriccetti** [comment]
Oh, unhappy face.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
