### ISSUE TITLE
Select ones with spaces are not loaded on edit

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#263]
#### Software versions 
JavaRosa v2.8.0 and older versions

#### Problem description
Select ones with spaces are not loaded on edit

[selectSpace.xml.txt](https://github.com/opendatakit/javarosa/files/1762519/selectSpace.xml.txt)
[selectSpace.xlsx](https://github.com/opendatakit/javarosa/files/1762520/selectSpace.xlsx)

#### Steps to reproduce the problem
1. Load the attached form.
2. Select "za munda" as a country and swipe.
3. Confirm the country is loaded on the next page.
4. Save the form, and confirm on the SD card (adb into the phone, cat the instances file) that the XML has the value
5. Edit the saved form in Collect.
6. Confirm that "za munda" is not available.
7. Save the form, and confirm on the SD card (adb into the phone, cat the instances file) that the value is gone.

#### Expected behavior
When a form is loaded, all values that are persisted are loaded.

#### Other information 
It was originally reported in the Collect's repository https://github.com/opendatakit/collect/issues/1942

I moved this issue here since it's related to Javarosa but I'm not sure if we want to fix it. 

The problem is that space is used as a choice name. 
![screenshot from 2018-02-27 12-54-20](https://user-images.githubusercontent.com/3276264/36727400-5eaefd64-1bbd-11e8-855e-239969c2b7ad.png)

We shouldn't use spaces in option names (names not displayed labels). If I try to do that using [ODK Build](https://build.opendatakit.org/) or XLSForm I'm informed about that:
![screenshot from 2018-02-27 12-56-54](https://user-images.githubusercontent.com/3276264/36727671-72e877dc-1bbe-11e8-954a-650446eacb62.png)

![screenshot from 2018-02-27 13-02-48](https://user-images.githubusercontent.com/3276264/36727697-8b0e80f4-1bbe-11e8-92e0-ddf8ca20794b.png)

looks like we can fix that issue for `selectOne` pretty easy https://github.com/grzesiek2010/javarosa/commit/549d05df71c53ba0b5e56fdff959bf59d8c3ca02

but the problem will still occur for `selectMultiple`. We use spaces as separators for multiple selected choices (in xml file) so we can't allow using spaces in names. If we want to fix the issue for both widgets we should add another separator for choices and not to use space for that.

@yanokwa since you have reported this issue let me know what you think.

**Comment by yanokwa** [comment]
I agree that we don't want to solve this with `select_multiple` because they are used for separators. But for `select_one` there is no reason that I can think of to prevent spaces. 

@martijnr does Enketo allow saving `select_one` values with spaces?

**Comment by grzesiek2010** [comment]
@yanokwa so probably we can use my fix https://github.com/grzesiek2010/javarosa/commit/549d05df71c53ba0b5e56fdff959bf59d8c3ca02

I'll test it and file a pr.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim --force

**Comment by MartijnR** [comment]
> @MartijnR does Enketo allow saving select_one values with spaces

It does, but its developer actually frowns upon this ;). My reasoning is that:

- it's confusing to users to have these different rules for such similar question types
- it should be possible to turn a select_one into a select_multiple without problems

**Comment by yanokwa** [comment]
Your reasoning is pretty sound, @MartijnR. Here's what I propose.

1. ODK Build prevents spaces on both. We should do nothing.
1. pyxform prevents spaces on select_multiple. We should add space prevention on select_one.
1. JavaRosa warns on both. We should do nothing.
1. Collect/JavaRosa doesn't properly save on select_one. We should change it so it saves.
1. Collect/JavaRosa doesn't properly save on select_multiple. We should add a little note to the widget warning people if they have a choice with spaces.

My vision here is that I don't want to break backward compatibility, but given that Collect can subtly throw away an answer, I think we should warn people.

**Comment by MartijnR** [comment]
Sounds great. I need to add a similar warning in Enketo, because the contents of external data are not checkable at the time of form validation, so there's always a chance for options with spaces to slip through.

**Comment by lognaturel** [comment]
@grzesiek2010 Please do issue a pull request, your fix looks good! 😊
