### ISSUE TITLE
An original repeatGroup child exists after reading answers using the populate method

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#266]
I noticed a strange behavior in the [populate](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/TreeElement.java#L708) method. 
I use a simple form with repeat group: 
[simpleFormWithRepeatGroup.xml.txt](https://github.com/opendatakit/javarosa/files/1771754/simpleFormWithRepeatGroup.xml.txt)
I fill this form adding three groups:
![screenshot_2018-03-01-16-42-41](https://user-images.githubusercontent.com/3276264/36853833-c348553c-1d6f-11e8-91df-45b11bc98cad.png)
In ODK Collect we call that mentioned [populate](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/TreeElement.java#L708) method from [FormLoaderTask](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java)

Here is what I see before calling [populate](https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/TreeElement.java#L708) method
![screenshot from 2018-03-01 17-04-06](https://user-images.githubusercontent.com/3276264/36854935-9a0b8b46-1d72-11e8-8cda-4aaf612e162f.png)

and after
![screenshot from 2018-03-01 17-04-52](https://user-images.githubusercontent.com/3276264/36854969-ae199ccc-1d72-11e8-9a3e-9f3e62b32b71.png)

**Four RepeatGroup instead of three. There the first one has only null values like before.**

The problem is here: https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/instance/TreeElement.java#L782 we add new elements for each filled group (in my case three times) but we never remove the original one. I tried to fix that in this way: https://github.com/grzesiek2010/javarosa/commit/5dde9852dd24d069ea9376e7d9a9233f8021ca84

everything works well I can't see any regression on the Collect's side.

I'm trying to use those elements to improve my current code https://github.com/opendatakit/collect/pull/1851
I found it's much better and the code is more readable but I need to ignore that first element in repeat groups. Could anyone tell me why it works in that way? Maybe my fix is ok...

**Comment by grzesiek2010** [comment]
@dcbriccetti do you know something about it? or maybe @mdudzinski

**Comment by lognaturel** [comment]
My initial thought is that the first group is the template. There doesn't seem to be any conditionals in case there is no template, though so I'm less certain. As a reminder, `jr:template` is an optional attribute. When present, it means that the group provides defaults and will not be included in the submitted record. See https://opendatakit.github.io/xforms-spec/#default-values-in-repeats

What if you remove `jr:template`? Do you still see the extra group?

What happens if you change 

```
          <RepeatGroup jr:template="">
            <Text2/>
          </RepeatGroup>
```

to 
```
          <RepeatGroup jr:template="">
            <Text2>Foo</Text2>
          </RepeatGroup>
```
and then fill out the form changing the `Text2` values to something other than Foo? Does the first group have `Text2` value `Foo`?

**Comment by grzesiek2010** [comment]
> What if you remove jr:template? Do you still see the extra group?

then in my first step (before calling the populate methods), I can see two repeat groups (it was one before) and after it's four like before.

> Does the first group have Text2 value Foo?

yes.

**Comment by grzesiek2010** [comment]
@lognaturel yes probably that extra element is needed as a template your second question helped me I tested it with changes I was thinking about https://github.com/grzesiek2010/javarosa/commit/5dde9852dd24d069ea9376e7d9a9233f8021ca84 and looks like it's for that. 

Thanks. I'm going to close this issue for now and handle this case on the Collect's side.
