### ISSUE TITLE
Calculates fire even when not relevant

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/javarosa#284]
> I agree that it's unexpected that calculates that are not relevant are evaluated. At the very least, it should be explicitly documented with the workaround that you used called out. I think we should also explore whether this was a deliberate choice or not and whether it would be possible to change.

From @lognaturel during the discussion at https://forum.opendatakit.org/t/odk-collect-calculate-fires-even-when-not-relevant/8923

**Comment by ggalmazor** [comment]
I think we have established in #516 that relevance is an UI concern that should not prevent any calculation. 

We could discuss whether this is convenient or not, or try to asses the performance implications in clients, but the specs are clear about it.
