### ISSUE TITLE
current() in choice filter is inconsistent with current() elsewhere

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#293]
This has come up because there's some desire to have pyxform output relative references in repeats: https://github.com/XLSForm/pyxform/issues/4. That would be in better conformance with W3C XForms and would allow for choice filters in repeats. Currently ${fieldname} syntax is always expanded to `/absolute/path/to/node` even when in a repeat. In W3C XForms, that should always evaluate to the first repeated element, not to the one in the current context. In ODK XForms, the repeat context is considered even when an absolute path is used. https://opendatakit.github.io/xforms-spec/#a-big-deviation-with-xforms

Unfortunately, JavaRosa interprets `current()` differently in a `choice-filter`. This was discussed at lengths in https://forum.opendatakit.org/t/current-in-xpath-predicate/4982 with no real conclusion reached for the broader ODK community.

As Mitch explained [in that thread](https://forum.opendatakit.org/t/current-in-xpath-predicate/4982/7):

> if you use a filter condition in the nodeset specification of a field "myfield", within that nodeset specification `"current()/.."` refers to the parent of the group enclosing the "myfield" field. It does not refer to the group enclosing the "myfield" field.

To be super explicit, `current()` in a `choice-filter` should refer to the node it is used from. Instead, it refers to the group enclosing the node.

As the thread discusses, the big challenge here is how to start generating relative references in form builders without resulting forms breaking on a bunch of devices that may have older clients.

One option is to change the `current()` behavior as quickly as possible. I expect relative paths in choice filters continue to be relatively rare. Then after some period of time has passed (a year?), form builders can start using relative paths and we can communicate to users that upgrading their clients is really important.

There are lots of ideas with flags and other ways of marking compatibility in the thread.

**Comment by MartijnR** [comment]
I wonder if doing a simple analysis to detect whether the XForm relies on the bug as follows would be sufficient to switch to `current-bug-compliant` mode in JavaRosa: 

If expression matches `/current\(\)\/[^.]+/` switch to `current-bug-compliant` mode.

This relies on the syntax where `current()/` is not followed by a `.` (or `..`). It may catch close to 100% of all the (very few) hand-coded forms that use current() currently. I would much prefer such a solution to tagging XForms for (likely) not relying on bugs.

**Comment by lognaturel** [comment]
I'm really not all that worried about breaking currently-existing forms. I don't expect there are very many and I think as long as we communicate it carefully it can be managed. But I think your idea is a very good one so thank you for that!

I'm more worried about the day when pyxform starts using relative references for choice filters. Ideally that day would be a while after this is fixed here and then I think we can avoid tagging XForms which I agree is ideal.

Ah, if only this had been addressed when it was first identified!!

**Comment by lognaturel** [comment]
Real human running into this: https://forum.opendatakit.org/t/indexed-repeat-problem/13821

Testing suggestions: https://forum.opendatakit.org/t/current-in-xpath-predicate/4982/14

**Comment by lognaturel** [comment]
If you were wondering whether it might be possible to change `qparent` to `q` at https://github.com/opendatakit/javarosa/blob/ae68403ceff8d5ed2fb5d8d09d4145523b337bf6/src/org/javarosa/xform/parse/XFormParser.java#L1323

you will be pleased to learn that it does indeed have the desired effect. I don't know what the consequences are yet.

Why can't we just set the nodeset ref right there? The comment note seems to have the key but I don't understand it yet: `note: this is only here because its currently impossible to both (a) get a form control's parent, and (b) convert expressions into refs while preserving predicates. once these are fixed, this field can go away`. We've run into this already with #298 so would really be good to get to the bottom of it.

**Comment by lognaturel** [comment]
I've put a form that illustrates the issue at https://github.com/opendatakit/javarosa/compare/master...lognaturel:javarosa-293 along with an exploratory test that I can't get to work quite right yet. I've had the most luck debugging from Collect. If you run the form there, you should see that the variety choices are never populated.

Now that I've looked at this more closely, I don't think we need to test every possible kind of use of `current()` (though it would be good to have some testing around it at some point). We're not planning to modify the way that XPath paths that include `current()` are interpreted, we just want to modify the context used to evaluated itemset predicates with `current()`. So I think for a robust test we need to come up with all ways `contextRef` is used in a node with dynamic itemsets.

Side note: In the ODK world we use the term "choice filters" to refer to XPath predicates used to limit chioces in a select. I use the two interchangeably.

I've been asking myself a series of questions and here are some answers so far.

**Can `.` be used everywhere that current() is used?**
No. The predicate (choice filter) case is the one where there's a difference. In an inner expression like a predicate, `.` is the tightest possible context whereas `current()` refers to the node the expression is in. See https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/current Otherwise they are interchangeable.

**When/where is the choice filter expression actually evaluated?**
`XPathPathExprEval.eval` calls `contextualize` as part of getting `matches` in `populateDynamicChoices` and that's where any paths in the choice filter expression are converted to absolute references. `matches` are the choices that satisfy the predicate. It's useful to set a breakpoint at the top of `XPathPathExprEval.eval` to watch this happen for any relative reference but especially for the choice filter ones that use `current()`. For the choice filters, we can see in the `contextualize` execution that the `EvaluationContext`'s `original` field is set one step too far back (the parent of the node).

`XPathPathExpr.getContextualizedTreeReference` sees that the `contextType` of the `TreeReference` representing the choice filter expression is 2. This was set by `XPathPathExpr.getReference()` when it encountered the text `current()` in the XPath expression. This means the `originalContext` (node that the choice filter is in) is used for contextualizing rather than the `contextRef` (choice filter expression itself). See the question on `.` vs. `current()` on why this is.

**What exactly is `ItemsetBinding.contextRef` used for?**
It's used to get an absolute reference from the `nodesetExpr` using `getAbsRef` in `initReference`. That absolute reference is used to do things like verify labels and values are actually children of the itemset.

The other place it's used is in figuring out `matches` as described above. There, it's used to contextualize the question node and the resulting reference is used as the context for evaluating the nodeset represented by the `nodesetExpr`. 

I believe all that means that using a relative expression for the nodeset itself (that is, not refering to another instance but refering to something like a repeat in the main instance) currently fails because the context is one level too high. That's the next thing I want to explore. Basically I think the title of this issue is a little misleading and it's really that any use of `current()` in a select node will be interpreted wrongly.

Pausing here to see if anyone else has questions or ideas.
