### ISSUE TITLE
randomize can't be used with choice filter that has comma

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#328]
#### Software versions 
JavaRosa v2.10.x

#### Problem description
Trying to randomize an itemset with a choice filter such as `randomize(instance('fruit')/root/item[selected(/filter-rank/fruit, name)])` leads to an error because whatever is after the comma tries to be used as a seed (in this case `name)]`).

#### Steps to reproduce the problem
1. Transfer a form with a randomized list with choice filter such as [filter-rank.xml.txt](https://github.com/opendatakit/javarosa/files/2134965/filter-rank.xml.txt)
1. Fill the form and see the error

#### Expected behavior
No error.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
I've created a PR with a solution. The solution relies on detecting a `[` in the nodeset definition, which would indicate a choice filter being used and, potentially, a comma in the first arg.

Can you think of more cases of a comma in the first arg which don't involve using the `[` in the nodeset definition?

**Comment by lognaturel** [comment]
That seems fine to me! I can't think of another case that would include a comma currently.
