### ISSUE TITLE
error: cannot find symbol method instance()

### ISSUE THREAD

**Issue by Divya21** [opendatakit/javarosa#346]
error: cannot find symbol method instance() is shown at the run time only.

Wherever the ReferenceManager.instance() is used, the error is shown on those lines. Even it has imported the right one i.e. :
import org.javarosa.core.reference.ReferenceManager;

While compiling, there is no error. In the gradle I have added the dependency of javarosa as mentioned below:
implementation("org.opendatakit:opendatakit-javarosa:2.10.0") {
        exclude group: 'joda-time'
        exclude group: 'org.slf4j'
    } 

Please help me out.

**Comment by lognaturel** [comment]
@Divya21 Can you explain what overall goal you're trying to achieve? Where are you using this code?
