### ISSUE TITLE
Output doesn't work in a text used as a jr:constraintMsg

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#36]
> Collect v1.5.1, on a Nexus 7 running Android 5.0.2
> 
> I created a form where calculate fields are used to create both a value used for a constraint and text to use in the constraint message. However, while the constraint itself seems to work correctly when I view the form on my tablet, the constraint message doesn't - instead of displaying my text from the calculate field, it displays e.g. "${0}". This same text works when I use it in a note instead. I've attached a sample form where this is reproduced.
> 
> Thanks,
> Laura

[constraintMessageError.xlsx](https://github.com/opendatakit/javarosa/files/919784/constraintMessageError.xlsx)

**Comment by lognaturel** [comment]
What's going on here is that `output` is not recognized when used in a `text` that is used as a `jr:constraintMsg`. See [constraintMessageError.txt](https://github.com/opendatakit/javarosa/files/1012482/constraintMessageError.txt) for a variation of the form that uses the exact same `text` for both the `label` and the `jr:constraintMsg`. 

The [XForm spec](https://opendatakit.github.io/xforms-spec/#body-elements) states that `output` is a "child of a &lt;label&gt; or &lt;hint&gt; element" [here](https://opendatakit.github.io/xforms-spec/#body-elements).

It looks like Enketo does support `output` when used in `jr:constraintMsg` (see [here](https://enketo.ona.io/x/#YDlb)). Perhaps we should expand the spec and support this.

**Comment by lognaturel** [comment]
I'll add that as can be seen [here](https://github.com/opendatakit/javarosa/blob/82be6fb967da741e4ceb8ba104e4b74767ffdbdf/src/org/javarosa/xform/parse/XFormParser.java#L979) and [here](https://github.com/opendatakit/javarosa/blob/82be6fb967da741e4ceb8ba104e4b74767ffdbdf/src/org/javarosa/xform/parse/XFormParser.java#L1067), `output` is supported specifically for `label` and `hint` currently. I think the ideal would be to allow it in arbitrary `text` as well.

**Comment by lognaturel** [comment]
More conversation about this at opendatakit/xforms-spec#125 that still needs to be finalized. The question is whether only calls on `jr:itext` should be allowed or whether other XPath functions should be evaluated.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
What would be a reasonable strategy to go about this? 

My instinct tells me to load the form inside a test, answer an instance with a `60` and then read the constraint error somehow. Is this feasible? Are there any examples of this kind of tests that I could study?

I've already discovered that on `XFormParserTest` I can `parse(r("constraint-message-error.xml"))` but right now I'm completely lost on what to do with my `ParseResult`... Any pointers?
