### ISSUE TITLE
Add support for range control

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#39]
See opendatakit/xforms-spec#109

**Comment by dcbriccetti** [comment]
I’m working on this.

**Comment by dcbriccetti** [comment]
What will this look like in Collect? I don’t see a suitable Android widget. Perhaps a `StringNumberWidget` tweaked to allow only values satisfying "start", "end", "step". Perhaps there should be an issue in Collect, and the discussion continued there?

**Comment by lognaturel** [comment]
I think opendatakit/collect#105 is the right place to discuss.

**Comment by dcbriccetti** [comment]
Notes from 4/27 brief conversation with @ctsims:

- 4/27 meeting, Dave and Clayton
	- Review change for adding range element and control.
		- The message at the bottom appears.
		- The error goes away if I pass these attributes ("start", "end", "step") to parseControl List<String> additionalUsedAtts, but then the attributes don’t get saved in the question additionalAttributes.
		- He thinks ODK added the additionalAttributes.
		- His recommendation: Extend QuestionDef or find some other way to pass the values.

```
Title: "Form with a Range"
XForm Parse Warning: Warning: 3 Unrecognized attributes found in Element [range] and will be ignored: [start,end,step] Location:
Problem found at nodeset: /html/body/range
With element <range ref="/stats/balance" start="-2.0" end="2.0" step="0.5"><label>
Problem found at nodeset: /html/body/range
With element <range ref="/stats/balance" start="-2.0" end="2.0" step="0.5"><label>
```

**Comment by dcbriccetti** [comment]
@mitchellsundt Do you remember what the additionalAttributes in QuestionDef are for?

**Comment by dcbriccetti** [comment]
Should this be closed? The work is done on the JavaRosa side, right?

**Comment by lognaturel** [comment]
Yes, thanks!!
