### ISSUE TITLE
External secondary instances don’t work

### ISSUE THREAD

**Issue by cooperka** [opendatakit/javarosa#390]
#### Software versions 
JavaRosa v2.12.1, Collect v1.18.0

#### Problem description
External secondary instances (see [docs](https://opendatakit.github.io/xforms-spec/#secondary-instances---external)) no longer work in Collect, seemingly due to JavaRosa issues.

1. There are errors parsing external XML
2. The external data location is extremely hard to access

#### Steps to reproduce the problem
1. Download the [form XML and data XML](https://drive.google.com/drive/folders/1l8LgfP0DXzTlH5YyjPIqNUNmvcOox8Og/)
1. Install an emulator using "Google APIs" (NOT "Google Play" because those don't support root access)
    - This is necessary because of a different regression; see notes below
1. `adb push internal_select_10.xml /sdcard/odk/forms/`
1. `adb push external_select_10.xml /sdcard/odk/forms/`
1. `adb root`
1. `adb shell`
1. As root:
    - `mount -o rw,remount rootfs /`
    - `mkdir /resources`
    - `exit`
1. `adb push external_data_10.xml /resources/`
1. Open the **external select 10** form

#### Expected behavior
The form should open and work normally, identically to **internal select 10**.

Additionally, external data should be stored at `/sdcard/odk/forms/external_select_10-media/`, not root `/resources/`. See [slack discussion](https://opendatakit.slack.com/archives/C35ENHA64/p1544186315008500?thread_ts=1544116019.006900&cid=C35ENHA64) with @grzesiek2010 for more context.

>I think we implemented changes on the javarosa side https://github.com/opendatakit/javarosa/pull/157/ but it doesn't work well in Collect.
>
> From logs, I can see that javarosa tries to read that file from /resources/external_data_10.xml where it should be  /storage/emulated/0/odk/forms/external_select_10-media/external_data_10.xml

#### Actual behavior
Form fails to parse:

```console
XFormParseException: <label> node for itemset doesn't exist! [instance(second)/root/item/itextId]
        at org.javarosa.xform.parse.FormInstanceParser.verifyItemsetBindings(FormInstanceParser.java:344)
```

#### Other information 
Here's the inspector value of `DataInstance fi` for internal vs. external forms:

Internal:

<img width="350" alt="fi internal" src="https://user-images.githubusercontent.com/2047062/49661412-fb787480-fa16-11e8-9fdf-ad407fef700c.png">

External:

<img width="350" alt="fi external" src="https://user-images.githubusercontent.com/2047062/49661413-fb787480-fa16-11e8-888e-483129afc9f6.png">

Breakpoint location: https://github.com/opendatakit/javarosa/blob/master@{2018-12-06}/src/org/javarosa/xform/parse/FormInstanceParser.java#L343

**Comment by ggalmazor** [comment]
Thanks for the detailed report, @cooperka!

This looks like it's connected to the comments at `ExternalDataInstance.java#getPathPrefix()`

```java
private static String getPathPrefix() {
    return System.getProperty("user.dir") + "/resources";
    /* ToDo find out how to get the actual location. Hélène says:
    Other "stuff outside the form" uses `<odk-form-folder>/<form-name>-media/` as the root dir but
    in this case all external secondary instances will go in the same folder. It would be good for
    that folder to reside in the odk root folder. We can come back to it.
    */
}
```

**Comment by dcbriccetti** [comment]
<img width="975" alt="work in progress" src="https://user-images.githubusercontent.com/55099/49956684-acb95780-feba-11e8-990b-e972795d8bd7.png">

Looks like it may be time to finish this “work in progress”.

**Comment by dcbriccetti** [comment]
I’m able to reproduce the 
`XFormParseException: <label> node for itemset doesn't exist! [instance(second)/root/item/itextId]` 
problem with @cooperka’s data.

**Comment by dcbriccetti** [comment]
Synthesizing a `TreeElement` above `root` allows the parse of @cooperka’s form. Does this seem like a reasonable solution, @ggalmazor and @cooperka?

<img width="1653" alt="screen shot 2018-12-16 at 4 02 50 pm" src="https://user-images.githubusercontent.com/55099/50060710-2caa2080-014c-11e9-9102-5f6492009d2a.png">

**Comment by dcbriccetti** [comment]
@cooperka, may we add your three files to our test suite?

**Comment by dcbriccetti** [comment]
Regarding where JavaRosa should look for the external data, @grzesiek2010, perhaps you can confirm that when Collect calls JavaRosa to parse the XML, 
```
fis = new FileInputStream(formXml);
FormDef formDefFromXml = XFormUtils.getFormFromInputStream(fis);
```
it doesn’t give enough information for JavaRosa to find the form’s media directory. Do you agree that we’ll need to modify the Collect -> JavaRosa interface to provide that information?

**Comment by cooperka** [comment]
> may we add your three files to our test suite?

Sure, absolutely :+1:

**Comment by ggalmazor** [comment]
> Do you agree that we’ll need to modify the Collect -> JavaRosa interface to provide that information?

How would it look like?

**Comment by dcbriccetti** [comment]
>How would it look like?

That’s up to us. We agree that JR shouldn’t be concerned with details about Collect file storage, right?

**Comment by ggalmazor** [comment]
> We agree that JR shouldn’t be concerned with details about Collect file storage, right?

Yes, JR should be given all it needs to work without making any assumptions about a particular client

**Comment by dcbriccetti** [comment]
How about overloading 
`XFormUtils.getFormFromInputStream(fis);`
A second argument could provide a path to external secondary instance forms.

**Comment by ggalmazor** [comment]
This is looking good! Thanks @dcbriccetti!

**Comment by dcbriccetti** [comment]
@cooperka, when you get a chance could you try your forms with https://github.com/opendatakit/javarosa/pull/394 and https://github.com/opendatakit/collect/pull/2771? Things seem to be working. Thanks!
@grzesiek2010, do you have any forms we could test with handy?

**Comment by grzesiek2010** [comment]
> do you have any forms we could test with handy?

No, I used the one provided by @cooperka
