### ISSUE TITLE
Add a function to calculate all possible options in select one and select multiple questions.

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#400]
#### Software versions 
JavaRosa v2.12.1 and older versions

#### Problem description
Some users need to be able to calculate all options in `select one` and `select multiple` questions.
Here is one topic: https://forum.opendatakit.org/t/counting-the-number-of-all-options-in-a-select-one-select-multiple-variable/17393 and I've seen at least two different.

**Comment by yanokwa** [comment]
@grzesiek2010 Can you link to the other threads you've seen?

**Comment by grzesiek2010** [comment]
For example:
https://forum.opendatakit.org/t/selecting-all-the-choices/17048
https://forum.opendatakit.org/t/counting-the-number-of-choices-available-not-those-which-are-selected-as-an-answer/13481

and probably more that I can't find now.

**Comment by lognaturel** [comment]
I don't think this should be a JavaRosa issue. This can already be done for secondary instances with `instance('<instance name>')/root/item[<choice filter>]`. If a choice filter is used, secondary instances are generated. https://forum.opendatakit.org/t/counting-the-number-of-all-options-in-a-select-one-select-multiple-variable/17393/12
