### ISSUE TITLE
Ensure formatted datetimes follow the spec's ISO8601 format

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/javarosa#404]
#### Problem description
Following the directions of the [ISO8601 adaptations doc](https://docs.google.com/document/d/1vPuEgapHvYWINnoa9QiG1R0HWMiCS4_8vtP_Zx3bGec/edit#heading=h.17wejfqu7qg9), we should fix how JR formats datetimes. Specifically, JR uses a wrong format when the time offset falls into whole hours:

- Wrong: `2019-02-11T16:04:45.638+07`
- Correct: `2019-02-11T16:04:45.638+07:00`

From the spec doc:
> JavaRosa doesn’t always use the correct offset format
> When the local timezone offset is of multiples of a full hour, it outputs this format:
> 
> [HH]:[MM]:[SS].[SSS]±[hh] as in 20:04:16.669+09
> 
> Only when the local timezone offset is of odd multiples of half an hour, it uses the format we want to use:
> 
> [HH]:[MM]:[SS].[SSS]±[hh]:[mm] as in 20:04:16.669+09:30
> 
> We should change JavaRosa to ensure it always adds the minutes fragment in the timezone offset text.

#### Other information 
Forum discussion bits:

[Clint says:](https://forum.opendatakit.org/t/odk-central-v0-1-alpha/13437/31?u=ggalmazor)
> it looks like the problem here is that whichever version of Collect you are using isn't outputting the correct date format. compare:
> 
> `2019-02-11T16:04:45.638+07`
> `2019-02-11T16:04:45.638+07:00`

[Gareth says:](https://forum.opendatakit.org/t/odk-central-v0-1-alpha/13437/35?u=ggalmazor)
> FYI I think it may be here: https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/core/model/utils/DateUtils.java
>
> ```java
> private static String formatTimeISO8601 (DateFields f) {
>   ...
>   String hrs = intPad(value / 60, 2);
>   String mins = value % 60 != 0 ? ":" + intPad(value % 60, 2) :"";
>   time += offsetSign + hrs + mins;
> ```
> ie if on hour it drops the mins off the (date)time suffix. On the surface it appears it could be a quick fix, in of itself, but given its potential impact elsewhere it could require some regression testing...?

**Comment by tiritea** [comment]
Given that any code consuming these iso8601 formatted dates should already be able to handle the case when having minutes, the fix might be a simple as changing the above suspected offending (?) line to:

`String mins = ":" + intPad(value % 60, 2);`

and making sure any date question results appearing in the resulting instance XML have ...+HH:MM

I'm happy to submit a trivial PR, but do you think this would constitute an adequate and sufficient test?

**Comment by ggalmazor** [comment]
> I'm happy to submit a trivial PR, but do you think this would constitute an adequate and sufficient test?

That'd be great. Let me know if you'd prefer me to do it.

There are a couple of tests in the `DateUtilsSCTOTests` class:

```java
@Test
public void testParseDateTime() {
    TimeZone.setDefault(TimeZone.getTimeZone("GMT+02"));

    Date date = DateUtils.parseDateTime("2014-10-05T00:03:05.244+03");
    String str = DateUtils.formatDateTime(date, DateUtils.FORMAT_ISO8601);

    assertEquals("2014-10-04T23:03:05.244+02", str);
}

@Test
public void testParseDateTime_withDST() {
    applyDST();

    Date date = DateUtils.parseDateTime("2014-10-05T00:03:05.244+03");
    String str = DateUtils.formatDateTime(date, DateUtils.FORMAT_ISO8601);

    assertEquals("2014-10-05T00:03:05.244+03", str);
}
```
I think that changing the assertions to `+02:00` and `+03:00` respectively would probably be enough, though I'd suggest adding extra cases:
- a `-04:00` case to test negative offsets
- a `Z` case to test the UTC time zone
- a `+01:30` to test half-hour multiple offsets

**Comment by tiritea** [comment]
If there's no immediate urgency I can test and submit a PR this weekend. I think I'll just fix the two existing tests for now - probably we should sit down and expressly enumerate all new tests that are now going to be needed to cover all the new supported formats that you've documented in https://docs.google.com/document/d/1vPuEgapHvYWINnoa9QiG1R0HWMiCS4_8vtP_Zx3bGec (rather than me tossing in a few more now just for the sake of it). 

thanks for identifying the tests for me! 

--------------------------------------------
On Thu, 2/14/19, Guillermo Gutiérrez <notifications@github.com> wrote:

 Subject: Re: [opendatakit/javarosa] Ensure formatted datetimes follow the spec's ISO8601 format (#404)
 To: "opendatakit/javarosa" <javarosa@noreply.github.com>
 Cc: "Dr. Gareth S. Bestor" <tiritea@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Thursday, February 14, 2019, 5:42 AM
 
 
 I'm happy to submit a trivial PR, but do you think
 this would constitute an adequate and sufficient test?
 
 That'd be great. Let me know if you'd prefer me
 to do it.
 There are a couple of tests in the
 DateUtilsSCTOTests class:
 @Test
 public void testParseDateTime() {
     TimeZone.setDefault(TimeZone.getTimeZone("GMT+02"));
 
     Date date = DateUtils.parseDateTime("2014-10-05T00:03:05.244+03");
     String str
 = DateUtils.formatDateTime(date, DateUtils.FORMAT_ISO8601);
 
     assertEquals("2014-10-04T23:03:05.244+02", str);
 }
 
 @Test
 public void
 testParseDateTime_withDST() {
     applyDST();
 
     Date date = DateUtils.parseDateTime("2014-10-05T00:03:05.244+03");
     String str
 = DateUtils.formatDateTime(date, DateUtils.FORMAT_ISO8601);
 
     assertEquals("2014-10-05T00:03:05.244+03", str);
 }
 I think that changing the assertions to
 +02:00 and +03:00 respectively
 would probably be enough, though I'd suggest adding
 extra cases:
 
 a -04:00 case to test negative offsets
 a Z case to test the UTC time zone
 a +01:30 to test half-hour multiple
 offsets
 
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ggalmazor** [comment]
That's perfectly fine, thanks!

**Comment by tiritea** [comment]
FYI I've made change in my fork but still need to rebuild my Collect and run some manual tests, and update testcases before submitting PR.

**Comment by tiritea** [comment]
I haven't been able to do any testing this week. Does this fix need to make it into the imminent Collect release (or can it wait till next one)? [I seem to recall it was a PITA for Central to workaround...]

**Comment by yanokwa** [comment]
March 20th is the hard deadline, but the earlier the better. Earlier means it can go into Collect with plenty of time for the testers to give it a go.

**Comment by tiritea** [comment]
I'll try to make time to run some tests this week - the patch itself is trivial.

**Comment by ggalmazor** [comment]
@tiritea, I'm on leave until March 1st, but if you need help, please, ping me. I'll probably be available to take a peek and add some brain-power to the testing part if you want.

**Comment by tiritea** [comment]
OK, maybe I'm doing something REALLY stupid here... but running a simple form with: 

      <bind nodeset="/data/datetime" required="false()" type="dateTime"/>

and with a simple test to echo the result in a read-only text note (label is = `datetime="${datetime}"`, I get the separate 'Select date' and 'Select time' input pickers in the Collect widget show up, but for the note - which should just be echoing the raw dateTime string result stored in the instance XML - I'm getting:

    datetime="2019-03-03" 

ie no time component whatsoever, yet alone a timezone offset?!? [this is all running off Android Studio simulator after installing latest Collect and javarosa from github master today]

Under Enketo, same form shows:
    
    datetime="2019-03-03T16:00:00.000+13:00" 

which is what I would have expected expect to see

I must be doing something completely braindead... (surely Collect's dateTime cant be that broken!)

**Comment by tiritea** [comment]
basically I'm trying a 'before' test to check Collect is indeed producing a datetime with no timezone offset minutes, before adding my patch. But I wasnt expecting not to get any time component at all! lol

**Comment by ggalmazor** [comment]
Hi @tiritea! Sorry for the delay in my feedback!

I think that involving Collect introduces too many moving parts, and that using a label as an indirect way of verifying what's going on with the datetime field might bring some unexpected results due to the way JR/Collect format values for output.

What we are trying to verify is that the XML document that JR produces when saving a document has the datetime field's value encoded in ISO8601 format. This is what the test should do:
1. Parse and load a form with one datetime field
2. Fill some value (you can also use a `calculate=now()` in the `<bind>` of that field and save this step)
3. Tell JR to produce an XML document from the filled form
4. Use KXML to parse the XML document, locate the node with the answer and check that the format of the value is an ISO8601 datetime, with an offset that's according to our specs.

**Comment by tiritea** [comment]
per conversation, it looks like Collect is doing some implicit reformatting when including instance XML node strings in label text, rather than displaying the expected raw string. I'll test actual resulting submission XML data instead.

But it appears there may be bug in this native 'reformatting-for-labels', since it appears to be dropping the time component when displaying a dateTime in a label (?)

**Comment by tiritea** [comment]
PR submitted. Passes tests but circleci packaging fails w/ "Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin...", which I'm pretty sure isnt anything I broke with my 1-liner change... Unfortunately I don have perms to just re-run the workflow.

I guess could try to resubmit the PR with a null change to see if github fixes itself... Any suggestions?

**Comment by tiritea** [comment]
Some more automated tests around this - ie end-to-end - would be far preferable to my manual test form; ala what @ggalmazor suggests. But I didn't want to hold up getting a PR with the necessary code change any longer, waiting for me to figure all that out...

**Comment by ggalmazor** [comment]
Thanks, @tiritea!

Since JR is a library that basically implements a workflow of XML > memory > XML, I think that a test that loads a blank form XML, does stuff in memory, generates a submission XML, and then checks the submission's contents, it pretty much qualifies as an end-to-end test to me :)

**Comment by tiritea** [comment]
I like your idea of an automated test that 'fakes' a submission, and reads the XML that will actually be sent back in to check its format. Especially given my earlier assumption that what gets echoed in a label is the raw unadulterated instance XML string value... which was wrong! Gawd only knows who else might potentially be interfering between javaRosa's formatTimeISO8601(), and what actually gets written out in the XML... :-) Checking the raw XML output is always best, if it can be readily accomplished.
