### ISSUE TITLE
jr:choice-name() broken when used in repeats

### ISSUE THREAD

**Issue by tiritea** [opendatakit/javarosa#435]
#### Software versions 
JavaRosa v1.x.x, Java v1.x.x, operating system

#### Problem description
jr:choice-name() always returns nothing when used against a select question inside a repeat loop. Probably due to the relative reference produced by pyxform for the quoted select question reference

ODK Forum discussion here: https://forum.opendatakit.org/t/problem-with-odk-calculation-field/19619

#### Steps to reproduce the problem
same form available from: https://forum.opendatakit.org/t/problem-with-odk-calculation-field/19619
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
#486 should address this. In an attempt to minimize context switching, @ggalmazor will wait a few more days to see if we can get another PR or two in for the next release.

**Comment by lognaturel** [comment]
Thanks for reporting, @Nova-Scotia! To confirm, you tried the exact same form without the `autocomplete` appearance and that worked as expected? If it's possible for you to share the form definition here or to build a quick demo of the issue, that would help with troubleshooting!

**Comment by Nova-Scotia** [comment]
Yes, I can share a minimal example - here's an XLS form where the appearance of the select_one question is set to autocomplete and the label cannot be obtained using jr:choice-name. If you switch the appearance to minimal, it works as expected. 

[Test_autocomplete_inside_repeat.xlsx](https://github.com/user-attachments/files/21420329/Test_autocomplete_inside_repeat.xlsx)

**Comment by Nova-Scotia** [comment]
@lognaturel, would it be better if I created a new issue?
