### ISSUE TITLE
Timing of the next JavaRosa update + interaction with Aggregate

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#49]
I had some very useful back and forth with @mitchellsundt about the JavaRosa update. He reminded me that if we include any significant structural changes, we'll need to update pyxform, the XLSForm web tool and Aggregate in addition to Briefcase, Collect and Validate.

I thought that if we were just adding XPath functions and making bug fixes, we didn't need to update Aggregate but @mitchellsundt mentioned that it might throw an exception on form parsing. If so, we'll need to coordinate with an Aggregate update to release even what we've merged so far. Mitch says that's going to happen before June 28th (ODK Summit). It would be very helpful if someone could do a quick sanity check on whether or not forms with unknown (to Aggregate) XPath functions cause a crash on Aggregate.

Adding structural changes like `range` or external secondary instances will definitely require an Aggregate update. @dcbriccetti 

I think all this means we may need to push our release to June in order to make sure we can update everything correctly. If we have it ready for early June, that should make it easier for @mitchellsundt to schedule the Aggregate release whenever is convenient for him. I don't think there's any problem with it going out before the other tools get updated since we wouldn't be breaking backwards compatibility, just making forward-looking improvements. Then everything else would get their JR update for the June 25th release (last Sunday of the month).

Alternately, I suppose we could update JR in some of the tools without announcing the new things it supports. That seems a bit strange but it would make the development of front ends on top of the new JR features a bit easier (e.g. `range`).

Would love some thoughts on this! @yanokwa @dcbriccetti @grzesiek2010

**Comment by lognaturel** [comment]
I've confirmed that adding XPath functions is no problem as far as Aggregate is concerned. I uploaded the form [trig_functions.txt](https://github.com/opendatakit/javarosa/files/1008930/trig_functions.txt) which includes a couple trig functions and the new `abs` function. I doing this, I realized that the version of JavaRosa that was shipped to Maven was actually based off ee74eb2. So it turns out the `abs` function has been out in the wild for almost a month now. 😳 Good news is that everything worked just fine.

Given that information, I think we should definitely ship a JR release corresponding to the current HEAD next week. It would be nice to include `range` as well if possible but not critical. We can bump external secondary instances since we'll have a lot more verification to do with those.

**Comment by dcbriccetti** [comment]
Did @mitchellsundt mean that Aggregate would have parse errors on new features even when its JavaRosa jar was updated?

**Comment by lognaturel** [comment]
We're just trying to figure out the limits of what we can add and use WITHOUT needing to update Aggregate's JR. It looks like adding XPath functions is fine. Probably not so for `range` but we'll need to double check that as well by uploading a form with a range and then uploading a filled out instance.

**Comment by lognaturel** [comment]
Big thanks to @mitchellsundt for releasing [Aggregate v1.4.14](https://github.com/opendatakit/opendatakit/wiki/Aggregate-Release-Notes#aggregate-v1414)!
