### ISSUE TITLE
Remove select and select1 bind types

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#501]
There is no such thing as `select` and `select1` bind types [in W3C XForms](https://www.w3.org/TR/xforms11/#ui-selectOne). In that spec, the bind type can be any simple type (see the spec for more details).

I believe the only action to be taken here is to change all `type="select1"` or `type="select"` in test forms to `type="string"`.

**Waiting to see whether any implementations need those types.**

If not, ODK XForms will remove them from [the binding examples](https://opendatakit.github.io/xforms-spec/#bindings):  https://github.com/opendatakit/xforms-spec/issues/25 

pyxform form will no longer output them: https://github.com/XLSForm/pyxform/issues/168

**Comment by ggalmazor** [comment]
This would be awesome!

I also agree that the expected type would be `string` because that's the type values in selects are given internally.

**Comment by ggalmazor** [comment]
> I believe the only action to be taken here is to change all type="select1" or type="select" in test forms to type="string".

We could always throw an error, or at least a warning in the logs if we see this type in a binding...

**Comment by lognaturel** [comment]
> We could always throw an error, or at least a warning in the logs if we see this type in a binding...

I think it's a good thing that unknown bind types fall back to string because it makes it possible for some data to be entered. I would not be in favor of throwing an error. I'm indifferent to adding to the logs -- in practice I don't think they're really accessed.
