### ISSUE TITLE
count-non-empty function doesn't work

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#509]
#### Software versions 
JavaRosa v2.17.0 and older versions

#### Problem description
[count-non-empty](https://docs.opendatakit.org/form-operators-functions/?highlight=count%20selected#count-non-empty) function doesn't work

#### Steps to reproduce the problem
Try to open this form: 
[test.xml.txt](https://github.com/opendatakit/javarosa/files/3803410/test.xml.txt)

**Comment by lognaturel** [comment]
I believe the fix here is to make the return type Double.
