### ISSUE TITLE
Re-introduce isParentOf as alias for isAncestorOf and mark as deprecated

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#519]
As @grzesiek2010 has discovered, `isParentOf` is used in Collect (https://github.com/opendatakit/collect/pull/3536/files) and really should be part of the public API.

**Comment by ggalmazor** [comment]
Thanks!

**Comment by ggalmazor** [comment]
Hi, @grzesiek2010! I'm not sure if you're working on this. I could throw a quick PR with the solution during my morning today

**Comment by grzesiek2010** [comment]
> Hi, @grzesiek2010! I'm not sure if you're working on this. I could throw a quick PR with the solution during my morning today

I had a Christmas break. I'll create a pr tomorrow.
