### ISSUE TITLE
Triggerables triggered twice on repeat creation

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#522]
A call on `triggerTriggerables` was introduced in `createNewRepeat` at https://github.com/opendatakit/javarosa/commit/9b88318435487f8fca91d60e67e0457b2a181d97#diff-96c7e556ff24192dbc4851b9b4410bbfR508. However, `dagImpl.createRepeatGroup` already makes the same call. The call on `triggerTriggerables` should be removed.

**Comment by ggalmazor** [comment]
The following couple of lines can be removed too, since are not used anymore:
```java
TreeReference parentRef = repeatContextRef.getParentRef();
TreeElement parentElement = mainInstance.resolveReference(parentRef);
```
