### ISSUE TITLE
Add test with form for digest function and ensure expressions for the first parameter are parsed

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#547]
Reported by @tiritea. This makes Validate fail so `digest` isn't accessible through XLSForm.

#### Problem description
The first argument to the `digest` function is cast to a `String` when it should be evaluated as an expression.

#### Steps to reproduce the problem
Write a form with some expression as the first argument to `digest`. 

#### Expected behavior
The expression should be evaluated and the digest of its result should be computed. Instead, it crashes.

**Comment by tiritea** [comment]
Presently digest(...) only works if you give it an explicit string, eg

`digest("ABCDE",'md5')`

But will fail to parse if you give it an Xpath ref expression, ala 

`digest(${foo}, 'md5')`

bugger... :-(
