### ISSUE TITLE
Set contents of audit meta element

### ISSUE THREAD

**Issue by nap2000** [opendatakit/javarosa#76]
#### Problem description
This is a feature request.
 
The [audit logging feature ](https://github.com/opendatakit/collect/pull/760)recently added to ODK collect is triggered by a form having an "audit" element inside the meta element. 
`<n0:meta xmlns:n0="http://openrosa.org/xforms">
    <n0:audit></n0:audit>
</n0:meta> `

If this element is present a csv file, audit.csv, containing the time spent in each question will is created and submitted back to the server along with the other collected data.

The audit element is not currently modified.  However according to the discussion [here](https://github.com/opendatakit/xforms-spec/issues/94#issuecomment-290172183) it should be set to a value corresponding to the filename containing the timing data.   

#### Proposed solution

The XML file with the results submitted to the server should have the contents of the audit element set to "audit.csv".

**Comment by lognaturel** [comment]
I think this info should be passed from the Collect side but I'm not totally sure. I would start by seeing how the nodes for other media types like images are populated.

**Comment by grzesiek2010** [comment]
Fixed in https://github.com/opendatakit/collect/pull/1384
