### ISSUE TITLE
support ranked selections

### ISSUE THREAD

**Issue by opendatakit-bot** [opendatakit/javarosa#79]
Originally reported by: **Yaw Anokwa (Bitbucket: [yanokwa](https://bitbucket.org/yanokwa), GitHub: [yanokwa](https://github.com/yanokwa))**

----------------------------------------

it would be nice to support questions that can ask: "please rank the following options from 1 to n".

----------------------------------------
- Bitbucket: https://bitbucket.org/javarosa/javarosa/issue/3

**Comment by lognaturel** [comment]
Duplicate of https://github.com/opendatakit/javarosa/pull/295
